Swal.fire({
  html: 'Por favor acepte nuestros <a href="termycond.html"> terminos y condiciones</a>',
  confirmButtonText: "Acepto",
  icon: "info",
  padding: "1 rem",
  backdrop: true,
  toast: true,
  position: "bottom",
  allowOutsideClick: false,
  allowEscapeKey: false,
  stopKeyDownPropagation: false,
  showConfirmButton: true,
  showCancelButton: false,
  showCloseButton: false,
  closeButtonAriaLabel: "Cerrar esta alerta",
});
